server:
  port: 8762

spring:
  application:
    name: hello-world-cn-provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    disable-html-escaping: true
    pretty-printing: true
    serialize-nulls: true