server:
  port: 8761

spring:
  application:
    name: hello-world-api

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  mvc:
    converters:
      preferred-json-mapper: gson

  gson:
    disable-html-escaping: true
    pretty-printing: true
    serialize-nulls: true

logging:
  level:
    co:
      featureflags: DEBUG
ffc:
  spring:
    env-secret: YTIxLTBlZTItNCUyMDIyMDcyMTAxMzAxOV9fMTU5X18yMTFfXzQyMl9fZGVmYXVsdF83YTMxNw==